@host = http://localhost:3000
@userId = 1
@productId = 5

GET {{host}}/products

POST {{host}}/products
Content-Type: application/json

{
  "category_id": null,
  "brand": "Xiaomi",
  "model": "Redmi Note 13",
  "description": "test",
  "price": 299,
  "stock": 50,
  "image_url": null
}

GET {{host}}/carts/{{userId}}

POST {{host}}/carts/{{userId}}/items
Content-Type: application/json

{
  "productId": {{productId}},
  "quantity": 2
}

POST {{host}}/carts/{{userId}}/items
Content-Type: application/json

{
  "productId": {{productId}},
  "quantity": 2
}

PATCH {{host}}/carts/{{userId}}/items/{{productId}}
Content-Type: application/json

{
  "quantity": 7
}

DELETE {{host}}/carts/{{userId}}/items/{{productId}}

DELETE {{host}}/carts/{{userId}}/items

POST {{host}}/carts/{{userId}}/items
Content-Type: application/json

{
  "productId": {{productId}},
  "quantity": 0
}

POST {{host}}/carts/{{userId}}/items
Content-Type: application/json

{
  "productId": 999999,
  "quantity": 1
}

PATCH {{host}}/carts/{{userId}}/items/999999
Content-Type: application/json

{
  "quantity": 3
}

DELETE {{host}}/carts/{{userId}}/items/999999

GET {{host}}/carts/abc
