### Configuración de Variables
@baseUrl = http://localhost:3000/users
@adminSecretKey = Adnsu8@we

### 1. Obtener todos los usuarios
GET {{baseUrl}}/
Content-Type: application/json

###

### 2. Crear un usuario común (Rol: 'user')
# @name createUser
POST {{baseUrl}}/
Content-Type: application/json

{
  "name": "Juan Perez",
  "email": "juan.perez@example.com",
  "password": "password123"
}

###

### Guardamos el ID del usuario creado para las siguientes pruebas
@createdUserId = {createUser.response.body.id}

### 3. Obtener un usuario por ID
GET {{baseUrl}}/{{createdUserId}}
Content-Type: application/json

###

### 4. Crear un Administrador (Validando la clave secreta)
POST {{baseUrl}}/admin
Content-Type: application/json

{
  "username": "admin_utn",
  "name": "Admin Universidad",
  "email": "admin@utn.edu",
  "password": "adminSecurePassword",
  "secretKey": "{{adminSecretKey}}"
}

###

### 5. Intentar crear Administrador con clave incorrecta (Debe dar 403)
POST {{baseUrl}}/admin
Content-Type: application/json

{
  "username": "hacker",
  "name": "Intruso",
  "email": "hacker@example.com",
  "password": "hack",
  "secretKey": "clave_incorrecta_2026"
}

###

### 6. Actualizar datos del usuario creado
PUT {{baseUrl}}/{{createdUserId}}
Content-Type: application/json

{
  "name": "Juan Carlos Perez",
  "username": "juan_carlos"
}

###

### 7. Eliminar al usuario creado
DELETE {{baseUrl}}/{{createdUserId}}
Content-Type: application/json

###

### 8. Intentar buscar al usuario eliminado (Debe dar 404)
GET {{baseUrl}}/{{createdUserId}}
Content-Type: application/json